(package! org-reverse-datetree)
;; (package! poetry)
;; (package! kubernetes)
;; (package! kubernetes-evil)
;; (package! kubel)
;; (package! kubel-evil)
;; (package! ivy-posframe)
;; (package! px :recipe (:host github :repo "aaptel/preview-latex"))
;; (package! golden-ratio)
(package! ox-ipynb :recipe (:host github :repo "jkitchin/ox-ipynb"))
;; (package! powerline)
(package! pfuture)
